### ISSUE TITLE
Support for parquet directories

### ISSUE THREAD

**Issue by Hoeze** [manojkarthick/pqrs#14]
Hi, I just tried your tool and I find it super useful :+1: 
However, I noticed that one cannot simply `cat` whole directories:
```bash
# pqrs cat vcf.parquet 
Error: ParquetError(General("underlying IO error: Is a directory (os error 21)"))
```
However, this works:
`pqrs cat vcf.parquet/**/*.parquet`

It would be a nice convenience function if pqrs could handle this case.

**Comment by manojkarthick** [comment]
Thanks @Hoeze!  I've added support for `cat`-ing parquet files recursively in directories with the [latest release](https://github.com/manojkarthick/pqrs/releases/tag/v0.2.0). Let me know if you face any issues.
