### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by GCPBigData** [manojkarthick/pqrs#23]
joserfjunior@Clodovil Downloads % pqrs cat FND_USER_CLEAN.parquet --json             

############################
File: FND_USER_CLEAN.parquet
############################

thread 'main' panicked at 'No such local time', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:173:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by manojkarthick** [comment]
Hi, could you please provide the `FND_USER_CLEAN.parquet` file so that I can try to reproduce the issue. Thanks!

**Comment by manojkarthick** [comment]
I will close this issue for now, I will reopen it to investigate if you could provide a sample. Thanks!
