### ISSUE TITLE
Schema Command Should Support Structured Output

### ISSUE THREAD

**Issue by dbready** [manojkarthick/pqrs#25]
Stumbled upon this project and it looks like a real missing link in parquet tooling.

For the `schema` subcommand, it would be nice if there was an optional way to output the data in a structured way (eg json) for consumption by other tools. Something like `pqrs schema data.parquet --json`. Ideally both the simple and detailed flags, but even capturing only the non-detailed data would be handy.

**Comment by manojkarthick** [comment]
Thanks @dbready - that's a good idea, I will look into this feature.
