### ISSUE TITLE
Don't show file header when outputting json

### ISSUE THREAD

**Issue by theduke** [manojkarthick/pqrs#27]
When using `pqrs cat --json` the output still contains the file headers for each file, making it much less useful for quickly converting a file or a bunch of files to JSON.

I feel like the headers should not be present at all when outputting JSON or CSV. There could be an additional flag to add them.

**Comment by manojkarthick** [comment]
The header is already removed when using `head` with the `--json` flag, and `cat` command should work the same way too. Thanks for opening the issue!
