### ISSUE TITLE
Hi, need help with the project?

### ISSUE THREAD

**Issue by robo555** [manojkarthick/pqrs#33]
Hi,

I was looking for a command line util to read Parquet files and found your project. I was wondering, would you be interested in contributions to the project, e.g. open issues, new features, etc?

I'm a software engineer (mostly backend for professional work), and recently took an interest in learning Rust. Practice is the best way to learn so let me know what you think!

Thanks, have a nice day

Robo

**Comment by levinotik** [comment]
Also, not to hijack this thread, but pqrs came in handy today in a huge way and just wanted to say thank you. I had accidentally deleted some data in our production DB. I was able to export a snapshot to S3 from RDS. The data is parquet so I needed a quick way to look at the data and figure out what I needed to restore `brew install manojkarthick/tap/pqrs` was all I needed. Thanks for the great work @manojkarthick!

**Comment by manojkarthick** [comment]
Hi @robo555 - thanks a lot! definitely, don't have any specific improvements I have in mind, but please feel free to propose any features you'd like to add!

**Comment by manojkarthick** [comment]
> Also, not to hijack this thread, but pqrs came in handy today in a huge way and just wanted to say thank you. I had accidentally deleted some data in our production DB. I was able to export a snapshot to S3 from RDS. The data is parquet so I needed a quick way to look at the data and figure out what I needed to restore `brew install manojkarthick/tap/pqrs` was all I needed. Thanks for the great work @manojkarthick!

that's amazing @levinotik! the quick look at the data was exactly why I initially created pqrs. Glad it was helpful! Hopefully everything went OK with the restore :)

**Comment by levinotik** [comment]
@manojkarthick indeed it did, thank you!!

**Comment by manojkarthick** [comment]
closing this issue for now, but will be happy to accept any help with the project @robo555 !
